// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    // Prisma 7 moved the seed command from package.json to here.
    // tsx is in devDependencies and available at build time.
    seed: "tsx ./prisma/seed.ts",
  },
  datasource: {
    // Migrate URL · unpooled if available (Neon's Vercel integration
    // populates DATABASE_URL_UNPOOLED automatically), else falls back
    // to DATABASE_URL for local dev where there's only one connection.
    url:
      process.env["DATABASE_URL_UNPOOLED"] ?? process.env["DATABASE_URL"],
  },
});
